### PR TITLE
[kidash] Remove support for kibana <6.x

### PR DESCRIPTION
**Pull request by valeriocos**
This code removes the support for kibana <6.x. Furthermore, it also removes the logic used in the past to convert 0/1 values to boolean in filters. That change was needed to allow the migration to <6.8, now for version >=6.8 it isn't needed anymore.

### CODE REVIEW

**Comment by imnitishng** [comment]
Hi @valeriocos, I believe this is done for supporting higher versions of ES and for the planned, ODFE support.
I would like to offer some help regarding this based on the GSoC idea.
I will open an issue for further discussions and start going through ODFE docs to plan out the roadmap.

**Comment by valeriocos** [comment]
Hi @imnitishng , thank you for your interest ! 

> Hi @valeriocos, I believe this is done for supporting higher versions of ES and for the planned, ODFE support.

Yes, in particular this PR removes some old logic that was added years ago to pass from 5.x to 6.x

> I would like to offer some help regarding this based on the GSoC idea.

Perfect, thanks! With the PR https://github.com/chaoss/grimoirelab-kidash/pull/38 and the new Kibiter image for 6.8.6 (https://github.com/chaoss/grimoirelab-kibiter), GrimoireLab can run on ODFE 0.10.0. However, some work is still needed to support more recent versions of ODFE.

In the upcoming weeks we need to update the docs (e.g., https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#source-code-and-docker-) and prepare some scripts to help the community migrating their env from 6.1 to 6.8. I have already something done, we can work together to improve and finalize it. WDYT?

**Comment by imnitishng** [comment]
> I have already something done, we can work together to improve and finalize it. WDYT? 

Yes sure I am ready to help with the work.
I have gone through the previous work done regarding this.
Can you guide me where to start?

**Comment by valeriocos** [comment]
Yes, sure! I have uploaded an initial version of the scripts.
- [sigilsmigration.py](https://gist.github.com/valeriocos/1069dee06181b3af2b778026a8d54f14)
  the scripts allows to:
  - identify the dashboards and index patterns in the .kibana not including a release date
  - generate the .grimoirelab-sigils index containing the ID of index patterns/dashboards together with their release date.
- [migration68.py](https://gist.github.com/valeriocos/f5030cefad3a93a70b9b154d2d14ae90)
  the script allows to migrate the .kibana from 6.1 to 6.8 (more details [here](https://gist.github.com/valeriocos/f5030cefad3a93a70b9b154d2d14ae90#file-migration68-py-L107))

These two scripts should be improved to be executed from the command line.

To check that the scripts work fine, you should have the containers for ES/Kibiter 6.1 running in your machine (https://github.com/chaoss/grimoirelab-sirmordred/blob/master/Getting-Started.md#getting-the-containers-), plus the ones for ES/Kibiter 6.8 (see docker-compose below as an reference). Make sure that they listen on different ports.

```
version: "3.7"
services:
  elasticsearch:
    restart: on-failure:5
    image: bitergia/elasticsearch:6.8.6-secured
    command: elasticsearch -Enetwork.bind_host=0.0.0.0 -Ehttp.max_content_length=2000mb
    environment:
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "127.0.0.1:6789:9200"
    volumes:
      - datavolume:/elasticsearch/data

  kibana:
    restart: on-failure:5
    image: bitergia/kibiter:secured-v6.8.6-2
    environment:
      - PROJECT_NAME=CHAOSS
      - NODE_OPTIONS=--max-old-space-size=1000
      - SUPPORT_ADDRESS=support@bitergia.com
      - ELASTICSEARCH_URL=https://elasticsearch:9200
      - ELASTICSEARCH_USER=kibanaserver
      - ELASTICSEARCH_PASSWORD=kibanaserver
    links:
      - elasticsearch
    ports:
      - "127.0.0.1:7890:5601"

# for completeness I left mariadb here
  mariadb:
    restart: on-failure:5
    image: mariadb:10.0
    expose:
      - "3306"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=test_sh
    command: --wait_timeout=2592000 --interactive_timeout=2592000 --max_connections=300 --character-set-server=utf8 --collation-server=utf8_unicode_ci --character-set-client-handshake=false

volumes:
  datavolume:
```

You should:
- upload some panels and the metadashboard (you can use micro-mordred with the flag --panels) to ES/Kibiter 6.1 to make sure that the .kibana isn't empty.
- execute sigilsmigration and finally the migration68. 

If everything goes ok, when starting ES/Kibiter 6.8 you should have a .kibana with the same data of the .kibana in 6.1 plus the .grimoirelab-sigils index.

We can move this work on a different issue and discuss the details there.

Thanks!

**Comment by imnitishng** [comment]
Okay, thank you for the detailed reply.
I will start off with checking the migration and report back to you with any suggestions or improvments.

**Review by alpgarcia — APPROVED** [review]
LGTM, I tested it with filters using numbers and booleans, and both work. I also uploaded a couple of index patterns without problems. I used Kibana 6.8.6 for all the tests.

**Pull request merged**
