### PR TITLE
[kidash] Disable kibiter 6 configuration

### PR DESCRIPTION
**Pull request by valeriocos**
This code temporarily disables the configuration of the default index pattern and time picker for kibiter 6.

### CODE REVIEW

**Review by sduenas — APPROVED** [review]
LGTM

**Comment by acs** [comment]
Why we are disabling it?

**Comment by valeriocos** [comment]
`kibana_settings_url = kibana_url + '/api/kibana/settings'` doesn't seem to work. It needs username and password to modify the settings. The call blocks also the integration tests too.

**Comment by acs** [comment]
> `kibana_settings_url = kibana_url + '/api/kibana/settings'` doesn't seem to work. It needs username and password to modify the settings. The call blocks also the integration tests too.

Yes, if you have SG installed and active, you need the auth settings so you can write in Elasticsearch indexes. But you can include the credentials in the URL for accessing kibana (i.e, http://login:passwd@localhost:5601). Is not possible to add the auth info to the URL?

**Comment by valeriocos** [comment]
yes, that's probably the best solution. I guess for the next release (not the one that is coming out now), this issue will be solved

**Pull request merged**
