### PR TITLE
[kidash] Load widgets by title

### PR DESCRIPTION
**Pull request by valeriocos**
This code changes the way of loading dashboards, searches and visualizations by their titles instead of their ids. Thus, this code allows to overcome the new way of generating ids in Kibana 6, which are hashed-based.

### CODE REVIEW

**Review by jgbarah — COMMENTED** [review]
I don't see how are you dealing when there are two or more items with the same title, which I think is possible in Kibana6 (they would have different ids). This could be a problem, because there could be no way of downloading the "second" item, and also a problem for inconsistency, because I guess there is no way of knowing in which orfer Kibana is goignto provide items with the same title.

I suggest that instead of this, you use a flag (--title, --id) to specify if the user is using the id or the title. Since the user can use --list, that would be would enough.

**Comment by valeriocos** [comment]
@jgbarah thank you for your comment. I agree with what you say, however from what I undestood when discussing with @alpgarcia, the idea was to use the title as an id to avoid the case you reported.

Currently, I'm not really familiar with the visualizations, so I don't have a clear view about the impact of the proposed change. I guess @alpgarcia or @dicortazar  can give a more complete answer to your comment.

**Comment by jgbarah** [comment]
Maybe somebody (eg, Bitergia devops) can have the discipline of always use identical title and id. But in general, if you edit a new dashboard in Kibana / Kibiter, nothing prevents you from using the same name, and then you get a new id. That's why I think it would be worth having some option (eg, --id) to force looking for the id, even if by default we use the  title. Otherwise, there is *no* way of downloading those dashboards with the same title... And what is worst, if you don't notice, it could happen that you download the wrong dashboard, because you didn't noticed the other one with the same title.

**Comment by valeriocos** [comment]
thank you @jgbarah, after talking with @alpgarcia and @acs the PR focuses only on the `clean_dashboard` method. In a nutshell, a panel is removed if the beginning of its title or ID matches the name of a data source.

**Review by acs — APPROVED** [review]
LGTM

**Comment by alpgarcia** [comment]
LGTM. Thanks @valeriocos!

@jgbarah this change only have effect when using `--data-sources` (e1d7522a5b7fdacbe4de1b2510b3977263d9bcd9 and ae60e4542a9715d08fb4828a509969317beb6e3d) option, which, for instance, is done by Mordred to filter out visualizations corresponding to inactive data sources/studies from Bitergia's Overview and Data Status panels, which by default includes visualizations for all available data sources.

All what you said above makes total sense for me. I think we need to revamp Kidash to store individual visualizations, filters, etc., as we do for index patterns, and then building panels by defining what you want in there, and not the oposite. IMHO, It's definitely something to include in Kidash roadmap.

**Pull request merged**
