### PR TITLE
[dashboard] Fix the bool filters for the dashboard

### PR DESCRIPTION
**Pull request by acs**
The 1/0 values are changed to True/False for kibana6 so the
filters work in this version.

### CODE REVIEW

**Comment by jgbarah** [comment]
I would rather have this code as a separate script, in the grimoirelab/panels repo. The script would load a KB5 json panel, and would produce a KB6 json panel. It could be a more general script fixing other stuff related to the migration to KB6, if that stuff appears (for now, we need at least fix font size, and maybe layout).

In fact, if the fix still allows the panels to work nicely in KB5, it would be a matter of just fixing them. If we need separate versions, I would rather produce separate versions, in separate directories, but likely that's a issue to discuss in grimoirelab/panels.

**Comment by acs** [comment]
Just a general comment: kibiter is also supporting the conversion of kibana5 panels format to kibana6. So the goal is to allow to reuse the kibana5 dashboards in kibana6 thanks to kidash conversions. If we find that this conversion is not possible because there are tons of issues, I will drop this goal. 

But if it is just modifying the bool filters and fonts size, I will do that in kidash so you don't need additional scripts that are hard to maintain. It is a fragile solution in general depending on scripts IMHO.

**Comment by jgbarah** [comment]
OK, Let's go this way you propose. But please, open an issue for making this conversion optional. I suggest using a flag to Kidash, such as `--avoid-conversions` to avoid conversions in case you want to upload exactly some panel to Kibiter. Any of us could implement it as soon as possible.

**Comment by acs** [comment]
But it is not a `conversion` but fixes that must be done so the dashboard can be used in Kibana 6. So IMHO it has no sense to add this `--avoid-fixes`. Do you agree?

**Pull request merged**
